"use client"

import Image from "next/image"

const TRAVELSTART_URL = "https://bit.ly/4gny4lv" // flights
const VIATOR_URL = "https://bit.ly/4poICor" // tours
const EXPEDIA_URL = "https://bit.ly/46APrvI" // hotels

export default function AffiliateBookingSection() {
  return (
      <section className="py-16 bg-white">
            <div className="container mx-auto px-4">
                    <div className="text-center mb-12">
                              <h2 className="text-3xl font-bold text-gray-900 mb-4">book with our trusted partners</h2>
                                        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                                                    choose from our verified travel partners for the best deals on flights, hotels, and experiences
                                                              </p>
                                                                      </div>

                                                                              <div className="grid gap-6 md:grid-cols-3">
                                                                                        {/* flights card */}
                                                                                                  <a
                                                                                                              href={TRAVELSTART_URL}
                                                                                                                          target="_blank"
                                                                                                                                      rel="noopener noreferrer"
                                                                                                                                                  className="rounded-2xl border border-gray-200 p-6 hover:shadow-lg hover:border-orange-300 transition-all duration-300 block"
                                                                                                                                                            >
                                                                                                                                                                        <div className="relative h-40 w-full overflow-hidden rounded-xl mb-4">
                                                                                                                                                                                      <Image
                                                                                                                                                                                                      src="/images/airplane-sunset.jpg"
                                                                                                                                                                                                                      alt="flights"
                                                                                                                                                                                                                                      fill
                                                                                                                                                                                                                                                      className="object-cover"
                                                                                                                                                                                                                                                                      sizes="(max-width: 768px) 100vw, 33vw"
                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 mb-2">
                                                                                                                                                                                                                                                                                                                          <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                          <span className="text-orange-600 font-bold">✈</span>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-xl font-semibold text-gray-800">flights</h3>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600">book flights at competitive rates with our trusted partner travelstart.</p>
                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                  {/* tours card */}
                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                        href={VIATOR_URL}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-2xl border border-gray-200 p-6 hover:shadow-lg hover:border-orange-300 transition-all duration-300 block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative h-40 w-full overflow-hidden rounded-xl mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="/images/travel-signpost.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt="tours & activities"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fill
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sizes="(max-width: 768px) 100vw, 33vw"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-2 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-orange-600 font-bold">🗺</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xl font-semibold text-gray-800">tours & activities</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-600">discover curated tours and experiences worldwide with viator.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* hotels card */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href={EXPEDIA_URL}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-2xl border border-gray-200 p-6 hover:shadow-lg hover:border-orange-300 transition-all duration-300 block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="relative h-40 w-full overflow-hidden rounded-xl mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          src="/images/beach-chairs.jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alt="hotels & stays"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fill
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sizes="(max-width: 768px) 100vw, 33vw"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-2 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-orange-600 font-bold">🏨</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xl font-semibold text-gray-800">hotels & stays</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">find comfortable stays worldwide with expedia’s trusted booking platform.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
