"use client"

import { Button } from "@/components/ui/button"

const TRAVELSTART_URL = "https://www.travelstart.com.ng/lp/affiliate/vingeltravels"
const VIATOR_URL =
  "https://www.viator.com/?m=33953&supag=1240250194145278&supca=676923706&supsc=kwd-77515991602646&supai=77515770892157&supdv=c&supnt=o&suplp=152628&supli=3169&supti=kwd-77515991602646&tsem=true&supci=kwd-77515991602646&gclsrc=3p.ds&pid=P00102658&mcid=42383&medium=link&campaign=vingel-website"
  const EXPEDIA_URL = "https://expedia.com/affiliate/VaSAcKD"

  export default function AffiliateSection() {
    return (
        <section className="py-20 bg-gray-50 fade-in-section">
              <div className="max-w-6xl mx-auto px-6 lg:px-8 text-center">
                      <h2 className="text-3xl font-bold mb-12 text-gray-900">Exclusive Travel Deals</h2>

                              <div className="grid gap-8 md:grid-cols-3">
                                        {/* Travelstart Card */}
                                                  <div className="rounded-2xl border border-gray-200 p-8 hover:shadow-lg transition-all duration-300 flex flex-col items-center">
                                                              <div className="h-16 w-16 mb-4 flex items-center justify-center rounded-full bg-green-500 text-white text-2xl font-bold">
                                                                            T
                                                                                        </div>
                                                                                                    <h3 className="text-xl font-semibold mb-2">Travelstart</h3>
                                                                                                                <p className="text-gray-600 mb-4">Affordable flights & hotel deals</p>
                                                                                                                            <Button className="btn-primary w-full" asChild>
                                                                                                                                          <a href={TRAVELSTART_URL} target="_blank" rel="noopener noreferrer">
                                                                                                                                                          Book on Travelstart
                                                                                                                                                                        </a>
                                                                                                                                                                                    </Button>
                                                                                                                                                                                              </div>

                                                                                                                                                                                                        {/* Viator Card */}
                                                                                                                                                                                                                  <div className="rounded-2xl border border-gray-200 p-8 hover:shadow-lg transition-all duration-300 flex flex-col items-center">
                                                                                                                                                                                                                              <div className="h-16 w-16 mb-4 flex items-center justify-center rounded-full bg-blue-500 text-white text-2xl font-bold">
                                                                                                                                                                                                                                            V
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                    <h3 className="text-xl font-semibold mb-2">Viator</h3>
                                                                                                                                                                                                                                                                                <p className="text-gray-600 mb-4">Tours & experiences worldwide</p>
                                                                                                                                                                                                                                                                                            <Button className="btn-primary w-full" asChild>
                                                                                                                                                                                                                                                                                                          <a href={VIATOR_URL} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                          Browse on Viator
                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                        {/* Expedia Card */}
                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-2xl border border-gray-200 p-8 hover:shadow-lg transition-all duration-300 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-16 w-16 mb-4 flex items-center justify-center rounded-full bg-yellow-500 text-white text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                            E
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-semibold mb-2">Expedia</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-600 mb-4">Unlock deals on hotels, flights & more</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button className="btn-primary w-full" asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href={EXPEDIA_URL} target="_blank" rel="noopener noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Book on Expedia
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
